config/routes.rb
Rails.application.routes.draw do
  resources :monthly_results

  post 'evaluations/create', controller: "evaluations", action: "create",  as: "create_evaluation"
  get 'evaluations/index', as: "evaluations"

  resources :questions

  get 'static_pages/api'
  get 'static_pages/about'
  get 'static_pages/doc'

  devise_for :users
  resources :functionaries

  resources :agencies

  root 'agencies#index'

end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :evaluations
	validates :question, :presence => true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @questions = Question.order("created_at")
    respond_with(@questions)
  end

  def show
    respond_with(@question)
  end

  def new
    @question = Question.new
    respond_with(@question)
  end

  def edit
  end

  def create
    @question = Question.new(question_params)
    respond_to do |format|
      if @question.save
        format.html { redirect_to questions_path, notice: 'Pregunta creada.' }
      else
        format.html { render :new }
      end
    end
    
  end

  def update
    @question.update(question_params)
    respond_to do |format|
      if @question.save
        format.html { redirect_to questions_path, notice: 'Pregunta actualizada.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: 'Pregunta eliminada.'
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:question, :agency_target, :agency_description, :agency_programs, :agency_contact, :functionary_functions, :functionary_schooling, :functionary_experience, :functionary_salary, :functionary_contact)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label class="control-label col-sm-2" for="question">Pregunta</label>
    <div class="col-sm-10">
      <%= f.text_area :question, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="agency_target">Campos de las dependecias</label>
    <div class="col-sm-10">
      <div class="checkbox">
        <label><%= f.check_box :agency_target %> Objetivos / Funciones </label>
      </div>

<!--       <div class="checkbox">
        <label><%#= f.check_box :agency_description %> Descripción </label>
      </div>
 -->
      <div class="checkbox">
        <label><%= f.check_box :agency_programs %> Proyectos / Programas </label>
      </div>
      <div class="checkbox">
        <label><%= f.check_box :agency_contact %> Información de contacto </label>
      </div>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="agency_target">Campos de los funcionarios</label>
    <div class="col-sm-10">
      <div class="checkbox">
        <label><%= f.check_box :functionary_functions %> Metas </label>
      </div>
      <div class="checkbox">
        <label><%= f.check_box :functionary_schooling %> Perfil académico </label>
      </div>
      <div class="checkbox">
        <label><%= f.check_box :functionary_experience %> Experiencia </label>
      </div>
      <div class="checkbox">
        <label><%= f.check_box :functionary_salary %> Salario </label>
      </div>
      <div class="checkbox">
        <label><%= f.check_box :functionary_contact %> Información de contacto </label>
      </div>
    </div>
  </div>

  <div class="form-group"> 
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Crear/Actualizar Pregunta", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editar Pregunta</h1>

<%= render 'form' %>

<%= link_to 'Regresar', questions_path %>

app/views/questions/index.html.erb
<h1>Lista de preguntas</h1>

<table class="table-hover table-striped text-center">
  <thead>
    <tr>
      <th></th>
      <th colspan="3" class="table-bordered text-center">Dependencia</th>
      <th colspan="5" class="table-bordered text-center">Funcionario</th>
      <th colspan="3"></th>
    </tr>
    <tr>
      <th class="col-md-10">Pregunta</th>
      <th class="col-sm-1">Objetivos/ Funciones</th>
      <th class="col-sm-1">Proyectos/ Programas</th>
      <th class="col-sm-1">Contacto</th>
      <th class="col-sm-1">Metas</th>
      <th class="col-sm-1">Perfil académico</th>
      <th class="col-sm-1">Experiencia</th>
      <th class="col-sm-1">Salario</th>
      <th class="col-md-4">Contacto</th>
      <th colspan="3" class="col-sm-1"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><br><%= question.question %><br><br></td>
        <td><%= '<i class="fa fa-check fa-2x"></i>'.html_safe if question.agency_target %></td>
        <td><%= '<i class="fa fa-check fa-2x"></i>'.html_safe if question.agency_programs %></td>
        <td><%= '<i class="fa fa-check fa-2x"></i>'.html_safe if question.agency_contact %></td>
        <td><%= '<i class="fa fa-check fa-2x"></i>'.html_safe if question.functionary_functions %></td>
        <td><%= '<i class="fa fa-check fa-2x"></i>'.html_safe if question.functionary_schooling %></td>
        <td><%= '<i class="fa fa-check fa-2x"></i>'.html_safe if question.functionary_experience %></td>
        <td><%= '<i class="fa fa-check fa-2x"></i>'.html_safe if question.functionary_salary %></td>
        <td><%= '<i class="fa fa-check fa-2x"></i>'.html_safe if question.functionary_contact %></td>
        <td><%= link_to '<i class="fa fa-pencil fa-2x"></i>'.html_safe, edit_question_path(question) %></td>
        <td><%= link_to '<i class="fa fa-trash-o fa-2x"></i>'.html_safe, question, method: :delete, data: { confirm: '¿Estás seguro de querer borrar esta pregunta?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Pregunta', new_question_path, class: "btn btn-primary" %>

app/views/questions/new.html.erb
<h1>Nueva Pregunta</h1>

<%= render 'form' %>

<%= link_to 'Regresar', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question.question %>
</p>

<p>
  <strong>Agency target:</strong>
  <%= @question.agency_target %>
</p>

<p>
  <strong>Agency description:</strong>
  <%= @question.agency_description %>
</p>

<p>
  <strong>Agency contact:</strong>
  <%= @question.agency_contact %>
</p>

<p>
  <strong>Functionary functions:</strong>
  <%= @question.functionary_functions %>
</p>

<p>
  <strong>Functionary schooling:</strong>
  <%= @question.functionary_schooling %>
</p>

<p>
  <strong>Functionary experience:</strong>
  <%= @question.functionary_experience %>
</p>

<p>
  <strong>Functionary salary:</strong>
  <%= @question.functionary_salary %>
</p>

<p>
  <strong>Functionary contact:</strong>
  <%= @question.functionary_contact %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>