config/routes.rb
Rails.application.routes.draw do
  resources :monthly_results

  post 'evaluations/create', controller: "evaluations", action: "create",  as: "create_evaluation"
  get 'evaluations/index', as: "evaluations"

  resources :questions

  get 'static_pages/api'
  get 'static_pages/about'
  get 'static_pages/doc'

  devise_for :users
  resources :functionaries

  resources :agencies

  root 'agencies#index'

end

app/models/monthly_result.rb
class MonthlyResult < ActiveRecord::Base
end

app/controllers/monthly_results_controller.rb
class MonthlyResultsController < ApplicationController
  before_action :set_monthly_result, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @monthly_results = MonthlyResult.order("evaluation desc").group_by{ |u| u.release.beginning_of_month }
    respond_to do |format|
      format.html
      format.json { render json: @monthly_results }
    end
  end

  def show
    respond_with(@monthly_result)
  end

  def new
    @monthly_result = MonthlyResult.new
    respond_with(@monthly_result)
  end

  def edit
  end

  def create
    @monthly_result = MonthlyResult.new(monthly_result_params)
    @monthly_result.save
    respond_with(@monthly_result)

    # MonthlyResult.new(release: , functionay: , image: , agency: , evaluation:, place: )
  end

  def update
    @monthly_result.update(monthly_result_params)
    respond_with(@monthly_result)
  end

  def destroy
    @monthly_result.destroy
    respond_with(@monthly_result)
  end

  private
    def set_monthly_result
      @monthly_result = MonthlyResult.find(params[:id])
    end

    def monthly_result_params
      params.require(:monthly_result).permit(:release, :functionay, :image, :agency, :evaluation, :place)
    end
end

app/helpers/monthly_results_helper.rb
module MonthlyResultsHelper
end

app/views/monthly_results/_form.html.erb
<%= form_for(@monthly_result) do |f| %>
  <% if @monthly_result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@monthly_result.errors.count, "error") %> prohibited this monthly_result from being saved:</h2>

      <ul>
      <% @monthly_result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :release %><br>
    <%= f.date_select :release %>
  </div>
  <div class="field">
    <%= f.label "Nombre del funcionario" %><br>
    <%= f.text_field :functionay %>
  </div>
  <div class="field">
    <%= f.label "Imagen del funcionario" %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label "Nombre de la dependencia" %><br>
    <%= f.text_field :agency %>
  </div>
  <div class="field">
    <%= f.label "Evaluación mensual" %><br>
    <%= f.text_field :evaluation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/monthly_results/edit.html.erb
<h1>Editar resultado mensual</h1>

<%= render 'form' %>

<%= link_to 'Back', monthly_results_path %>

app/views/monthly_results/index.html.erb
<h1>Resultados mensuales</h1>
<% meses = %w[meses Enero Febrero Marzo Abril Mayo Junio Julio Agosto Septiembre Octubre Noviembre Diciembre] %>

<% @monthly_results.each do |monthly_result| %>
  <div class="row">
    <h3><%= meses[monthly_result[0].month] %>, <%= monthly_result[0].year %></h3>
    <hr>
  </div>

    <% result = monthly_result[1].first %>
    <div class="row">
      <div class="col-md-2">
        <%= image_tag result.image, style: "max-width:100%;max-height:200px;", class: "center-block" %><br>
        <strong><%= result.functionay %></strong><br>
        <%= result.agency %><br>
        <%= result.evaluation %><br>
        <% if current_user and current_user.is_admin? %>
          <br><%= link_to 'Editar', edit_monthly_result_path(result) %> | 
          <%= link_to 'Borrar', result, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    <div class="col-md-10">
    <% monthly_result[1].each_with_index do |result, i| %>
      <% if i > 0 %>
      <div class="col-sm-1">
        <%= result.evaluation %><br>
        <%= image_tag result.image, style: "max-width:130%;max-height:90px;", class: "center-block" %>
        <% if current_user and current_user.is_admin? %>
          <%= link_to 'Editar', edit_monthly_result_path(result) %> | 
          <%= link_to 'Borrar', result, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
      <% end %>
      <% if i == 11 %>
        </div>
        <div class="row">
      <% end %>
    <% end %>
    </div>

    </div>

<% end %>

<br>

<%= link_to 'Nuevo resultado mensual', new_monthly_result_path if current_user and current_user.is_admin? %>
<!--  -->

app/views/monthly_results/new.html.erb
<h1>Nuevo resultado mensual</h1>

<%= render 'form' %>

<%= link_to 'Back', monthly_results_path %>

app/views/monthly_results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Release:</strong>
  <%= @monthly_result.release %>
</p>

<p>
  <strong>Functionay:</strong>
  <%= @monthly_result.functionay %>
</p>

<p>
  <strong>Image:</strong>
  <%= @monthly_result.image %>
</p>

<p>
  <strong>Agency:</strong>
  <%= @monthly_result.agency %>
</p>

<p>
  <strong>Evaluation:</strong>
  <%= @monthly_result.evaluation %>
</p>

<p>
  <strong>Place:</strong>
  <%= @monthly_result.place %>
</p>

<%= link_to 'Edit', edit_monthly_result_path(@monthly_result) %> |
<%= link_to 'Back', monthly_results_path %>