config/routes.rb
Rails.application.routes.draw do
  resources :monthly_results

  post 'evaluations/create', controller: "evaluations", action: "create",  as: "create_evaluation"
  get 'evaluations/index', as: "evaluations"

  resources :questions

  get 'static_pages/api'
  get 'static_pages/about'
  get 'static_pages/doc'

  devise_for :users
  resources :functionaries

  resources :agencies

  root 'agencies#index'

end

app/models/agency.rb
class Agency < ActiveRecord::Base
	has_one :functionary

	validates :name, :presence => true
	validates :ordering, :presence => true

	def contact
		"Teléfono: " + phone + ". Dirección: " + address + "."
	end
end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  before_action :set_agency, only: [:show, :edit, :update, :destroy]

  # GET /agencies
  # GET /agencies.json
  def index
    @agencies = Agency.order("ordering")
  end

  # GET /agencies/1
  # GET /agencies/1.json
  def show
    @functionary = @agency.functionary
  end

  # GET /agencies/new
  def new
    @agency = Agency.new
  end

  # GET /agencies/1/edit
  def edit
  end

  # POST /agencies
  # POST /agencies.json
  def create
    @agency = Agency.new(agency_params)

    respond_to do |format|
      if @agency.save
        format.html { redirect_to @agency, notice: 'Agency was successfully created.' }
        format.json { render :show, status: :created, location: @agency }
      else
        format.html { render :new }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agencies/1
  # PATCH/PUT /agencies/1.json
  def update
    respond_to do |format|
      if @agency.update(agency_params)
        format.html { redirect_to @agency, notice: 'Agency was successfully updated.' }
        format.json { render :show, status: :ok, location: @agency }
      else
        format.html { render :edit }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agencies/1
  # DELETE /agencies/1.json
  def destroy
    @agency.destroy
    respond_to do |format|
      format.html { redirect_to agencies_url, notice: 'Agency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agency
      @agency = Agency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agency_params
      params.require(:agency).permit(:name, :address, :phone, :ordering, :programs, :description, :target, :latitude, :longitude, :logo)
    end
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/views/agencies/_form.html.erb
<%= form_for(@agency, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @agency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agency.errors.count, "error") %> prohibited this agency from being saved:</h2>

      <ul>
      <% @agency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label class="control-label col-sm-2" for="name">Nombre de la dependencia</label>
    <div class="col-sm-10">
      <%= f.text_field :name, size: 50, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="logo">Logo</label>
    <div class="col-sm-10">
      <%= f.text_field :logo, size: 50, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="phone">Teléfono</label>
    <div class="col-sm-10">
      <%= f.text_field :phone, size: 50, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="ordering">Numeración en pantalla principal</label>
    <div class="col-sm-10">
      <%= f.text_field :ordering, size: 50, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="address">Dirección</label>
    <div class="col-sm-10">
      <%= f.text_area :address, size: "150x3", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="target">Objetivo de la dependencia (Aparece en la pantalla principal)</label>
    <div class="col-sm-10">
      <%= f.text_area :target, size: "150x5", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="description">Decripción de la dependencia</label>
    <div class="col-sm-10">
      <%= f.text_area :description, size: "150x5", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="programs">Proyectos / Programas</label>
    <div class="col-sm-10">
      <%= f.text_area :programs, size: "150x5", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="latitude">Latitude</label>
    <div class="col-sm-10">
      <%= f.text_field :latitude, size: 50, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="longitude">Longitude</label>
    <div class="col-sm-10">
      <%= f.text_field :longitude, size: 50, class: "form-control" %>
    </div>
  </div>

  <div class="form-group"> 
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Crear/Actualizar Dependencia", class: "btn btn-primary" %>
    </div>
  </div>

<% end %>

app/views/agencies/edit.html.erb
<h1>Editar Dependencia</h1>

<%= render 'form' %>

<%= link_to 'Regresar', @agency %>

app/views/agencies/index.html.erb
<p>
  <strong>Sigue a tu funcionario</strong> pretende ser el medio por el cual la ciudadanía pueda informarse acerca de las actividades y objetivos de las dependencias de gobierno y sus titulares y, con base en ello, poder evaluar a los funcionarios.
</p>
<p>
  Elije una dependencia, conoce qué hace, cómo lo hace y quién está al frente de ella y, ¡evalúa su desempeño!<strong>*</strong>.
</p>
<small>(*) Necesitas registrarte para evaluar a tu funcionario, es rápido y gratuito. <br>
Esta página está optimizada para su vista en dispositivos móviles.</small>
<%= link_to 'Nueva Dependencia', new_agency_path, class: "btn btn-primary", style: "float: right;" if current_user and current_user.is_admin?%>
<br>
<br>

<div class="list-group">
  <a href="#" class="list-group-item active">
    Dependencias
  </a>
  <% @agencies.each do |agency| %>
    <a href="<%= agency_path(agency.id) %>" class="list-group-item">
      <div class="row" >
        <div class="container">
          <%= image_tag agency.logo, style: "float: left; margin: 5px 30px 0 0;" %>
          <%= image_tag agency.functionary.photo, style: "float: right; max-height:80px; margin: 5px 30px 0 0;" %>
          <h3><%= agency.name %></h3>
          Titular: <strong><%= agency.functionary.fullname if agency.functionary %></strong> <br>
          <%= agency.address %> <br>
        </div>
      </div>
      <div class="row" style="margin: 10px 10px 0 0;" >
        <%= GitHub::Markdown.render_gfm(agency.target).html_safe %>

        <%#= agency.target %>
      </div>
    </a>
    <% if current_user and current_user.is_admin? %>
      <%= link_to 'Editar', edit_agency_path(agency) %> | 
      <%= link_to 'Eliminar', agency, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  <% end %>
</div>

<br>

app/views/agencies/new.html.erb
<h1>Nueva Dependencia</h1>

<%= render 'form' %>

<%= link_to 'Regresar', @agency %>

app/views/agencies/show.html.erb
<div class="row">
  <% if @agency.functionary.present? %>
    <div style="float: right;" >
      <% if current_user %>
        <%= link_to 'Evaluar funcionario', evaluations_path(agency_id: @agency.id), class: "btn btn-primary" %>
      <% else %>
        <a href="#" data-toggle="modal" data-target="#singup_modal" id="button-to-signup" class="btn btn-primary">Registrarse</a>
        <a href="#" data-toggle="modal" data-target="#login_modal" id="button-to-login" class="btn btn-primary">Entrar</a>
        <br>Regístrate para evaluar.
      <% end %>
    </div>
  <% end %>
  
  <h2><%= @agency.name %></h2><br><br>
  <div class="col-md-4">
    <%= image_tag @agency.logo %>
    <p>
      <br><br>
      <strong><i class="fa fa-building-o"></i></strong> 
      <%= @agency.address %>
    </p>
    <p>
      <% if @agency.phone? %>
        <strong><i class="fa fa-phone"></i></strong>
        <%= @agency.phone %>
      <% end %>
    </p>

    <% if current_user and current_user.is_admin? %>
      <%= link_to 'Editar Dependencia', edit_agency_path(@agency) %> |
      <%= link_to 'Regresar', agencies_path %>
    <% end %>

  </div>

  <div class="col-md-8">
    <%= GitHub::Markdown.render_gfm(@agency.target).html_safe if @agency.target %>
    <%= GitHub::Markdown.render_gfm(@agency.description).html_safe if @agency.description %>

    <p>
      <strong>Proyectos / Programas</strong>
      <%= GitHub::Markdown.render_gfm(@agency.programs).html_safe if @agency.programs %>
    </p>
  </div>
</div>

<hr>
<div class="row">
  <% if @agency.functionary.present? %>
    <div style="float: right;" >
      <% if current_user %>
        <%= link_to 'Evaluar funcionario', evaluations_path(agency_id: @agency.id), class: "btn btn-primary" %>
      <% else %>
        <a href="#" data-toggle="modal" data-target="#singup_modal" id="button-to-signup" class="btn btn-primary">Registrarse</a>
        <a href="#" data-toggle="modal" data-target="#login_modal" id="button-to-login" class="btn btn-primary">Entrar</a>
        <br>Regístrate para evaluar.
      <% end %>
    </div>
    <h2>Titular</h2>

    <div class="col-md-4">
      <p>
        <%= image_tag @functionary.photo, style: "max-width:80%;", class: "center-block" %>
      </p>

      <p>
        <strong><%= @functionary.fullname %></strong>
        
      </p>
      <p>
        <b><i class="fa fa-building-o"></i></b>
        <%= @functionary.office_address %>
      </p>

      <p>
        <b><i class="fa fa-phone"></i></b>
        <%= @functionary.phone %>
      </p>

      <p>
        <b><i class="fa fa-envelope"></i></b>
        <%= @functionary.email %>
      </p>

      <p>
        <b>Evaluación de este mes: </b>
        <strong><%= @functionary.evaluation? ? "%0.2f" % @functionary.evaluation : 0.0 %></strong>
      </p>

      <% if current_user and current_user.is_admin? %>
        <%= link_to 'Editar Funcionario', edit_functionary_path(@functionary) %> |
        <%= link_to 'Regresar', agencies_path %>
      <% end %>
    </div>


    <div class="col-md-8">
      <p>
        <h3>Metas:</h3>
        <%= @functionary.functions.present? ? GitHub::Markdown.render_gfm(@functionary.functions).html_safe : "Información no disponible" %>
      </p>

      <p>
        <h3>Perfil Académico:</h3>
        <%= @functionary.schooling.present? ? GitHub::Markdown.render_gfm(@functionary.schooling).html_safe : "Información no disponible" %>
      </p>

      <p>
        <h3>Experiencia:</h3>
        <%= @functionary.experience.present? ? GitHub::Markdown.render_gfm(@functionary.experience).html_safe : "Información no disponible" %>
      </p>

      <p>
        <h3>Salario:</h3>
        <%= @functionary.salary.present? ? GitHub::Markdown.render_gfm(@functionary.salary).html_safe : "Información no disponible" %>
      </p>
    </div>

    <br><br><br>
  <% elsif current_user and current_user.is_admin? %>
    <br><%= link_to 'Agregar Titular', new_functionary_path(agency_id: @agency.id), class: "btn btn-primary" %>
  <% end %>
</div>

<script type="text/javascript">
  $( document ).ready(function() {
    $( "table" ).addClass( "table" );
  });
</script>