config/routes.rb
Rails.application.routes.draw do
  resources :monthly_results

  post 'evaluations/create', controller: "evaluations", action: "create",  as: "create_evaluation"
  get 'evaluations/index', as: "evaluations"

  resources :questions

  get 'static_pages/api'
  get 'static_pages/about'
  get 'static_pages/doc'

  devise_for :users
  resources :functionaries

  resources :agencies

  root 'agencies#index'

end

app/models/functionary.rb
class Functionary < ActiveRecord::Base
	belongs_to :agency
	has_many :evaluations

	validates :fname, :presence => true
	validates :lname, :presence => true

	def fullname
		fname + " " + lname
	end

	def contact
		return "Teléfono: " + phone + ". Email: " + email + ". Oficina: " + office_address + "."
	end
end

app/controllers/functionaries_controller.rb
class FunctionariesController < ApplicationController
  before_action :set_functionary, only: [:show, :edit, :update, :destroy]

  # GET /functionaries
  # GET /functionaries.json
  def index
    @functionaries = Functionary.all
  end

  # GET /functionaries/1
  # GET /functionaries/1.json
  def show
  end

  # GET /functionaries/new
  def new
    @functionary = Functionary.new
    id = params[:functionary] ? params[:functionary][:agency_id] : params[:agency_id]
    @agency = Agency.find(id)
  end

  # GET /functionaries/1/edit
  def edit
    @agency = @functionary.agency
  end

  # POST /functionaries
  # POST /functionaries.json
  def create
    @functionary = Functionary.new(functionary_params)

    respond_to do |format|
      if @functionary.save
        format.html { redirect_to @functionary.agency, notice: 'Functionary was successfully created.' }
        format.json { render :show, status: :created, location: @functionary }
      else
        format.html { render :new }
        # format.html { render :new, :locals => {agency_id: params[:agency_id]} }
        format.json { render json: @functionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /functionaries/1
  # PATCH/PUT /functionaries/1.json
  def update
    respond_to do |format|
      if @functionary.update(functionary_params)
        format.html { redirect_to @functionary.agency, notice: 'Functionary was successfully updated.' }
        format.json { render :show, status: :ok, location: @functionary }
      else
        format.html { render :edit }
        format.json { render json: @functionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /functionaries/1
  # DELETE /functionaries/1.json
  def destroy
    @functionary.destroy
    respond_to do |format|
      format.html { redirect_to functionaries_url, notice: 'Functionary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_functionary
      @functionary = Functionary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def functionary_params
      params.require(:functionary).permit(:fname, :lname, :photo, :phone, :email, :office_address, :functions, :agency_id, :charge, :salary, :schooling, :experience, :evaluation)
    end
end

app/helpers/functionaries_helper.rb
module FunctionariesHelper
end

app/views/functionaries/_form.html.erb
<%= form_for(@functionary, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @functionary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@functionary.errors.count, "error") %> prohibited this functionary from being saved:</h2>

      <ul>
      <% @functionary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :agency_id, value: @agency ? @agency.id : params[:functionary][:agency_id] %>
  <%= f.hidden_field :agency_name, value: @agency ? @agency.name : params[:functionary][:agency_name] %>
  Para la dependencia <strong><%= @agency ? @agency.name : params[:functionary][:agency_name] %></strong> <br><br>

  <div class="form-group">
    <label class="control-label col-sm-2" for="fname">Nombre(s)</label>
    <div class="col-sm-10">
      <%= f.text_field :fname, size: 50, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="lname">Apellido(s)</label>
    <div class="col-sm-10">
      <%= f.text_field :lname, size: 50, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="photo">Foto</label>
    <div class="col-sm-10">
      <%= f.text_field :photo, size: 50, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="charge">Cargo</label>
    <div class="col-sm-10">
      <%= f.text_field :charge, size: 50, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="office_address">Dirección de oficina</label>
    <div class="col-sm-10">
      <%= f.text_field :office_address, size: 50, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="phone">Teléfono</label>
    <div class="col-sm-10">
      <%= f.text_field :phone, size: 50, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="email">Correo electrónico</label>
    <div class="col-sm-10">
      <%= f.text_field :email, size: 50, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="salary">Salario</label>
    <div class="col-sm-10">
      <%= f.text_area :salary, size: "50x7", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="functions">Metas</label>
    <div class="col-sm-10">
      <%= f.text_area :functions, size: "150x15", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="schooling">Perfil académico</label>
    <div class="col-sm-10">
      <%= f.text_area :schooling, size: "150x15", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="experience">Experiencia</label>
    <div class="col-sm-10">
      <%= f.text_area :experience, size: "150x15", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="evaluation">Evaluación</label>
    <div class="col-sm-10">
      <%= f.text_field :evaluation, size: 50, class: "form-control" %>
    </div>
  </div>

  <div class="form-group"> 
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Crear/Actualizar Funcionario", class: "btn btn-primary" %>
    </div>
  </div>

<% end %>

app/views/functionaries/edit.html.erb
<h1>Editar Funcionario</h1>

<%= render 'form' %>

<%= link_to 'Regresar', @agency %>

app/views/functionaries/index.html.erb
<h1>Listing functionaries</h1>

<table>
  <thead>
    <tr>
      <th>Fname</th>
      <th>Lname</th>
      <th>Photo</th>
      <th>Agency</th>
      <th>Charge</th>
      <th>Salary</th>
      <th>Schooling</th>
      <th>Experience</th>
      <th>Evaluation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @functionaries.each do |functionary| %>
      <tr>
        <td><%= functionary.fname %></td>
        <td><%= functionary.lname %></td>
        <td><%= functionary.photo %></td>
        <td><%= functionary.agency %></td>
        <td><%= functionary.charge %></td>
        <td><%= functionary.salary %></td>
        <td><%= functionary.schooling %></td>
        <td><%= functionary.experience %></td>
        <td><%= functionary.evaluation %></td>
        <td><%= link_to 'Show', functionary %></td>
        <td><%= link_to 'Edit', edit_functionary_path(functionary) %></td>
        <td><%= link_to 'Destroy', functionary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Functionary', new_functionary_path %>

app/views/functionaries/new.html.erb
<h1>Nuevo Funcionario</h1>

<%= render 'form' %>

<%= link_to 'Regresar', @agency %>

app/views/functionaries/show.html.erb
<p>
  <strong>Nombre(s):</strong>
  <%= @functionary.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @functionary.lname %>
</p>

<p>
  <%= image_tag @functionary.photo %>
</p>

<p>
  <strong>Agency:</strong>
  <%= link_to @functionary.agency.name, agency_path(@functionary.agency.id) %>
</p>

<p>
  <strong>Charge:</strong>
  <%= @functionary.charge %>
</p>

<p>
  <strong>Salary:</strong>
  <%= GitHub::Markdown.render_gfm(@functionary.salary).html_safe %>
  <%#= @functionary.salary %>
</p>

<p>
  <strong>Perfil Académico:</strong>
  <%= GitHub::Markdown.render_gfm(@functionary.schooling).html_safe %>
  <%#= @functionary.schooling %>
</p>

<p>
  <strong>Experiencia:</strong>
  <%= GitHub::Markdown.render_gfm(@functionary.experience).html_safe %>
  <%#= @functionary.experience %>
</p>

<p>
  <strong>Evaluation:</strong>
  <%= @functionary.evaluation %>
</p>

<%= link_to 'Editar', edit_functionary_path(@functionary) %> |
<%= link_to 'Regresar', functionaries_path %>